baseURL: https://ralphptorr.es/
languageCode: en-us
title: Ralph Torres
theme: aether

params:
  brand: ⑈ ralphptorr.es
  description: Physics undergraduate student
  rssinmenu: true
  # bgimg: /img/pattern-ignasi.png
  # headshotimg: /img/home-side.jpg

disableKinds:
  - term

markup:
  markup.highlight:
    style: igor

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true